# Generated by Django 3.2.3 on 2021-06-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210601_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentportfolio',
            name='HistoryTransactions',
        ),
        migrations.RemoveField(
            model_name='currentportfolio',
            name='status',
        ),
        migrations.AddField(
            model_name='currentportfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
