# Generated by Django 3.2.3 on 2021-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210602_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentportfolio',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
