# Generated by Django 3.2.3 on 2021-06-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_currentportfolio_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytransactions',
            name='transaction_id',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
