# Generated by Django 3.2.3 on 2021-06-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_historytransactions_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentportfolio',
            name='average_price_portfolio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentportfolio',
            name='company_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
